### ISSUE TITLE
DbContext extensions leaking into all other projects

### ISSUE THREAD

**Issue by devel112** [zzzprojects/EntityFrameworkCore#14]
Im using another package with the same extensions for DbContext and this package is overriding all uses, even if it's not included in the other projects within the same solution

**Comment by JonathanMagnan** [comment]
Hello @devel112 ,

This is how extension methods work ;(

There is not so much we can do about it. However, you can use extern alias on your side to only show those extensions in files you want to use them: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern-alias

Best Regards,

Jonathan

**Comment by devel112** [comment]
Ty!
